[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bit_field = "0.10"

[build-dependencies]
cc = "1.2"

[[bin]]
name = "kernel"
src = "src/main.rs"
test = false
bench = false
